name: Deploy Docs to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Zip the docs folder
        run: zip -r docs.zip docs/
      
      - name: Upload docs to S3
        run: aws s3 cp docs.zip s3://${{ secrets.S3_BUCKET_NAME }}/docs.zip
      #Copy the zip from S3 Bucket to EC2 instance, unzip and then delete the zip file
      #Since this is only for the static website files, no other action is required
      - name: Execute SSM command to deploy docs on EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters commands=["aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/docs.zip /tmp/docs.zip","unzip -o /tmp/docs.zip -d ${{ secrets.TARGET_PATH_ON_EC2 }}","rm /tmp/docs.zip"] \
            --region ${{ secrets.AWS_REGION }} \
            --output text
